# Generated by Django 4.0.5 on 2022-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_remove_contact_img_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Общедоступный контакт'),
        ),
    ]
